spring:
  application:
    name: TestTaskBot

  datasource:
    url: jdbc:postgresql://localhost:5432/testtaskbot
    user:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true # debug
    open-in-view: false
    hibernate:
      ddl-auto: validate
